name: Test nightly

on:
  schedule:
    - cron: '13 0,12 * * *' # Regulary every 12 hours
      
jobs:
  test-integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Start minikube
        uses: konveyor/tackle2-operator/.github/actions/start-minikube@main
      - name: Build image in minikube
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          make docker-build
      - name: Install Tackle
        uses: konveyor/tackle2-operator/.github/actions/install-tackle@main
        with:
          tackle-hub-image: tackle2-hub:latest
          tackle-image-pull-policy: IfNotPresent
      - name: Set host and namespace
        run: |
          echo "host=$(minikube ip)/hub" >> $GITHUB_ENV
          echo "namespace=$(kubectl get tackles.tackle.konveyor.io --all-namespaces --no-headers | awk '{print $1}')" >> $GITHUB_ENV
      - name: Test execution
        run: |
          HUB_BASE_URL="http://$(minikube ip)/hub" make test-integration
        with:
          host: ${{ env.host }}
